function [ cat_name, cat_ind, cat_color ] = get_mscoco_cat_info(  )

% cat_name
cat_name{1}  = 'person & Accessory';
cat_name{2}  = 'Animal';
cat_name{3}  = 'Vehicle';
cat_name{4}  = 'Outdoor Objects';
cat_name{5}  = 'Sports';
cat_name{6}  = 'Kitchenware';
cat_name{7}  = 'Food';
cat_name{8}  = 'Furniture';
cat_name{9}  = 'Appliance';
cat_name{10} = 'Electronics';
cat_name{11} = 'Indoor Objects';

cat_color = distinguishable_colors(15);

cat_ind(1)  = 1;  % person
cat_ind(2)  = 3;  % bicycle
cat_ind(3)  = 3;  % car
cat_ind(4)  = 3;  % motorcycle
cat_ind(5)  = 3;  % airplace
cat_ind(6)  = 3;  % bus
cat_ind(7)  = 3;  % train
cat_ind(8)  = 3;  % truck
cat_ind(9)  = 3;  % boat
cat_ind(10) = 4;  % traffic_light
cat_ind(11) = 4;  % fire_hydrant
cat_ind(12) = 4;  % street_sign
cat_ind(13) = 4;  % stop_sign
cat_ind(14) = 4;  % parking_meter
cat_ind(15) = 4;  % bench
cat_ind(16) = 2;  % bird
cat_ind(17) = 2;  % cat
cat_ind(18) = 2;  % dog
cat_ind(19) = 2;  % horse
cat_ind(20) = 2;  % sheep
cat_ind(21) = 2;  % cow
cat_ind(22) = 2;  % elephant
cat_ind(23) = 2;  % bear
cat_ind(24) = 2;  % zebra
cat_ind(25) = 2;  % giraffe
cat_ind(26) = 1;  % hat
cat_ind(27) = 1;  % backpack
cat_ind(28) = 1;  % umbrella
cat_ind(29) = 1;  % shoe
cat_ind(30) = 1;  % eye_glasses
cat_ind(31) = 1;  % handbag
cat_ind(32) = 1;  % tie
cat_ind(33) = 1;  % suitcase
cat_ind(34) = 5;  % frisbee
cat_ind(35) = 5;  % skis
cat_ind(36) = 5;  % snowboard
cat_ind(37) = 5;  % sports_ball
cat_ind(38) = 5;  % kite
cat_ind(39) = 5;  % baseball_bat
cat_ind(40) = 5;  % baseball_glove
cat_ind(41) = 5;  % skateboard
cat_ind(42) = 5;  % surfboard
cat_ind(43) = 5;  % tennis_racket
cat_ind(44) = 6;  % bottle
cat_ind(45) = 6;  % plate
cat_ind(46) = 6;  % wine_glass
cat_ind(47) = 6;  % cup
cat_ind(48) = 6;  % fork
cat_ind(49) = 6;  % knife
cat_ind(50) = 6;  % spoon
cat_ind(51) = 6;  % bowl
cat_ind(52) = 7;  % banana
cat_ind(53) = 7;  % apple
cat_ind(54) = 7;  % sandwich
cat_ind(55) = 7;  % orange
cat_ind(56) = 7;  % broccoli
cat_ind(57) = 7;  % carrot
cat_ind(58) = 7;  % hot_dog
cat_ind(59) = 7;  % pizza
cat_ind(60) = 7;  % donut
cat_ind(61) = 7;  % cake
cat_ind(62) = 8;  % chair
cat_ind(63) = 8;  % couch
cat_ind(64) = 8;  % potted plant
cat_ind(65) = 8;  % bed
cat_ind(66) = 8;  % mirror
cat_ind(67) = 8;  % dining_table
cat_ind(68) = 8;  % window
cat_ind(69) = 8;  % desk
cat_ind(70) = 8;  % toilet
cat_ind(71) = 8;  % door
cat_ind(72) = 10; % tv
cat_ind(73) = 10; % laptop
cat_ind(74) = 10; % mouse
cat_ind(75) = 10; % remote
cat_ind(76) = 10; % keyboard
cat_ind(77) = 10; % cell_phone
cat_ind(78) = 9;  % microwave
cat_ind(79) = 9;  % oven
cat_ind(80) = 9;  % toaster
cat_ind(81) = 9;  % sink
cat_ind(82) = 9;  % refrigerator
cat_ind(83) = 9;  % blender
cat_ind(84) = 11; % book
cat_ind(85) = 11; % clock
cat_ind(86) = 11; % vase
cat_ind(87) = 11; % scissors
cat_ind(88) = 11; % teddy_bear
cat_ind(89) = 11; % hair_drier
cat_ind(90) = 11; % toothbrush
cat_ind(91) = 11; % hair_brush

end

